//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsRetriever.AppData {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    public sealed partial class DownloadConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static DownloadConfig defaultInstance = ((DownloadConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DownloadConfig())));
        
        public static DownloadConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.clashroyale.com/v1/clans/%23{{CLAN_TAG}}/members")]
        public string members_URL {
            get {
                return ((string)(this["members_URL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImE5ZTE1ODhiLWYwY2QtNDMwNi1hNTBhLTc4M2E0YzY2OTE1MSIsImlhdCI6MTYwNzI4Nzk2Miwic3ViIjoiZGV2ZWxvcGVyLzQzZDg3MDJiLTFmMDctYzg4OC0wNjM5LWQ1YjE3YjdiN2UzNCIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIzNy4xODguMTYyLjIyOSIsIjE3OC4yNTUuMTY4LjE1NiIsIjM3LjE4OC4xODMuMTg4Il0sInR5cGUiOiJjbGllbnQifV19.kxPDOGlMzdU7q-Nn1iQMZTI9FVoMZ0E0Pv8BXC-FvURSHv0_0mzgJG5b94xtWJC-Yjj9UcGNaoGHfsvmTrIdTQ")]
        public string _Token {
            get {
                return ((string)(this["_Token"]));
            }
            set {
                this["_Token"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.clashroyale.com/v1/clans/%23{{CLAN_TAG}}/currentriverrace")]
        public string currentRiverRace_URL {
            get {
                return ((string)(this["currentRiverRace_URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.clashroyale.com/v1/players/%23{{PLAYER_TAG}}")]
        public string playersInfo_URL {
            get {
                return ((string)(this["playersInfo_URL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9UU2Y92J")]
        public string CLAN_TAG {
            get {
                return ((string)(this["CLAN_TAG"]));
            }
            set {
                this["CLAN_TAG"] = value;
            }
        }
    }
}
