//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsRetriever.AppData {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    public sealed partial class DownloadConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static DownloadConfig defaultInstance = ((DownloadConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DownloadConfig())));
        
        public static DownloadConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.clashroyale.com/v1/clans/%23{{CLAN_TAG}}/members")]
        public string members_URL {
            get {
                return ((string)(this["members_URL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjRiZTBlODZlLTk2YzEtNDUxNS1iNDEwLTEzNmVmMmRkNGMwYyIsImlhdCI6MTYwNzAzNjE4Mywic3ViIjoiZGV2ZWxvcGVyLzQzZDg3MDJiLTFmMDctYzg4OC0wNjM5LWQ1YjE3YjdiN2UzNCIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxNzguMjU1LjE2OC4xNTYiLCIzNy4xODguMTgzLjE4OCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.M_7KjeAd0C6VPOcy8jqIJGROv6FT4VirZUN-qBpsy7N_ayhPZedT7SRR61sdMR4KZUdVXthOun2UY1naPa-rRQ")]
        public string _Token {
            get {
                return ((string)(this["_Token"]));
            }
            set {
                this["_Token"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.clashroyale.com/v1/clans/%23{{CLAN_TAG}}/currentriverrace")]
        public string currentRiverRace_URL {
            get {
                return ((string)(this["currentRiverRace_URL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9UU2Y92J")]
        public string CLAN_TAG {
            get {
                return ((string)(this["CLAN_TAG"]));
            }
            set {
                this["CLAN_TAG"] = value;
            }
        }
    }
}
